
@cenum var"##Ctag#2157"::UInt32 begin
  UNSET_FILE_FORMAT = 0
  ASCII = 1
  BINARY = 2
  NETCDF3_CLASSIC = 3
  NETCDF3_64BIT_OFFSET = 4
  NETCDF4_CLASSIC = 5
  NETCDF4 = 6
end

@cenum var"##Ctag#2158"::UInt32 begin
  LITTLE = 0
  BIG = 1
end

@cenum var"##Ctag#2159"::UInt32 begin
  FROM_DEFAULT = 0
  FROM_VEGLIB = 1
  FROM_VEGPARAM = 2
  FROM_VEGHIST = 3
end

@cenum var"##Ctag#2160"::UInt32 begin
  AIR_TEMP = 0
  ALBEDO = 1
  CATM = 2
  CHANNEL_IN = 3
  FCANOPY = 4
  FDIR = 5
  LAI = 6
  LWDOWN = 7
  PAR = 8
  PREC = 9
  PRESSURE = 10
  VP = 11
  SWDOWN = 12
  WIND = 13
  SKIP = 14
  N_FORCING_TYPES = 15
end

@cenum var"##Ctag#2161"::UInt32 begin
  OUT_ASAT = 0
  OUT_LAKE_AREA_FRAC = 1
  OUT_LAKE_DEPTH = 2
  OUT_LAKE_ICE = 3
  OUT_LAKE_ICE_FRACT = 4
  OUT_LAKE_ICE_HEIGHT = 5
  OUT_LAKE_MOIST = 6
  OUT_LAKE_SURF_AREA = 7
  OUT_LAKE_SWE = 8
  OUT_LAKE_SWE_V = 9
  OUT_LAKE_VOLUME = 10
  OUT_ROOTMOIST = 11
  OUT_SMFROZFRAC = 12
  OUT_SMLIQFRAC = 13
  OUT_SNOW_CANOPY = 14
  OUT_SNOW_COVER = 15
  OUT_SNOW_DEPTH = 16
  OUT_SOIL_ICE = 17
  OUT_SOIL_LIQ = 18
  OUT_SOIL_ICE_FRAC = 19
  OUT_SOIL_LIQ_FRAC = 20
  OUT_SOIL_MOIST = 21
  OUT_SOIL_WET = 22
  OUT_SURFSTOR = 23
  OUT_SURF_FROST_FRAC = 24
  OUT_SWE = 25
  OUT_WDEW = 26
  OUT_ZWT = 27
  OUT_ZWT_LUMPED = 28
  OUT_BASEFLOW = 29
  OUT_DELINTERCEPT = 30
  OUT_DELSOILMOIST = 31
  OUT_DELSURFSTOR = 32
  OUT_DELSWE = 33
  OUT_DISCHARGE = 34
  OUT_EVAP = 35
  OUT_EVAP_BARE = 36
  OUT_EVAP_CANOP = 37
  OUT_INFLOW = 38
  OUT_LAKE_BF_IN = 39
  OUT_LAKE_BF_IN_V = 40
  OUT_LAKE_BF_OUT = 41
  OUT_LAKE_BF_OUT_V = 42
  OUT_LAKE_CHAN_IN = 43
  OUT_LAKE_CHAN_IN_V = 44
  OUT_LAKE_CHAN_OUT = 45
  OUT_LAKE_CHAN_OUT_V = 46
  OUT_LAKE_DSTOR = 47
  OUT_LAKE_DSTOR_V = 48
  OUT_LAKE_DSWE = 49
  OUT_LAKE_DSWE_V = 50
  OUT_LAKE_EVAP = 51
  OUT_LAKE_EVAP_V = 52
  OUT_LAKE_PREC_V = 53
  OUT_LAKE_RCHRG = 54
  OUT_LAKE_RCHRG_V = 55
  OUT_LAKE_RO_IN = 56
  OUT_LAKE_RO_IN_V = 57
  OUT_LAKE_VAPFLX = 58
  OUT_LAKE_VAPFLX_V = 59
  OUT_PET = 60
  OUT_PREC = 61
  OUT_RAINF = 62
  OUT_REFREEZE = 63
  OUT_RUNOFF = 64
  OUT_SNOW_MELT = 65
  OUT_SNOWF = 66
  OUT_SUB_BLOWING = 67
  OUT_SUB_CANOP = 68
  OUT_SUB_SNOW = 69
  OUT_SUB_SURFACE = 70
  OUT_TRANSP_VEG = 71
  OUT_WATER_ERROR = 72
  OUT_ALBEDO = 73
  OUT_BARESOILT = 74
  OUT_FDEPTH = 75
  OUT_LAKE_ICE_TEMP = 76
  OUT_LAKE_SURF_TEMP = 77
  OUT_RAD_TEMP = 78
  OUT_SALBEDO = 79
  OUT_SNOW_PACK_TEMP = 80
  OUT_SNOW_SURF_TEMP = 81
  OUT_SNOWT_FBFLAG = 82
  OUT_SOIL_TEMP = 83
  OUT_SOIL_TNODE = 84
  OUT_SOIL_TNODE_WL = 85
  OUT_SOILT_FBFLAG = 86
  OUT_SURF_TEMP = 87
  OUT_SURFT_FBFLAG = 88
  OUT_TCAN_FBFLAG = 89
  OUT_TDEPTH = 90
  OUT_TFOL_FBFLAG = 91
  OUT_VEGT = 92
  OUT_ADV_SENS = 93
  OUT_ADVECTION = 94
  OUT_DELTACC = 95
  OUT_DELTAH = 96
  OUT_ENERGY_ERROR = 97
  OUT_FUSION = 98
  OUT_GRND_FLUX = 99
  OUT_IN_LONG = 100
  OUT_LATENT = 101
  OUT_LATENT_SUB = 102
  OUT_MELT_ENERGY = 103
  OUT_LWNET = 104
  OUT_SWNET = 105
  OUT_R_NET = 106
  OUT_RFRZ_ENERGY = 107
  OUT_SENSIBLE = 108
  OUT_SNOW_FLUX = 109
  OUT_AERO_COND = 110
  OUT_AERO_COND1 = 111
  OUT_AERO_COND2 = 112
  OUT_AERO_RESIST = 113
  OUT_AERO_RESIST1 = 114
  OUT_AERO_RESIST2 = 115
  OUT_AIR_TEMP = 116
  OUT_CATM = 117
  OUT_DENSITY = 118
  OUT_FCANOPY = 119
  OUT_FDIR = 120
  OUT_LAI = 121
  OUT_LWDOWN = 122
  OUT_PAR = 123
  OUT_PRESSURE = 124
  OUT_QAIR = 125
  OUT_REL_HUMID = 126
  OUT_SWDOWN = 127
  OUT_SURF_COND = 128
  OUT_VP = 129
  OUT_VPD = 130
  OUT_WIND = 131
  OUT_ADV_SENS_BAND = 132
  OUT_ADVECTION_BAND = 133
  OUT_ALBEDO_BAND = 134
  OUT_DELTACC_BAND = 135
  OUT_GRND_FLUX_BAND = 136
  OUT_IN_LONG_BAND = 137
  OUT_LATENT_BAND = 138
  OUT_LATENT_SUB_BAND = 139
  OUT_MELT_ENERGY_BAND = 140
  OUT_LWNET_BAND = 141
  OUT_SWNET_BAND = 142
  OUT_RFRZ_ENERGY_BAND = 143
  OUT_SENSIBLE_BAND = 144
  OUT_SNOW_CANOPY_BAND = 145
  OUT_SNOW_COVER_BAND = 146
  OUT_SNOW_DEPTH_BAND = 147
  OUT_SNOW_FLUX_BAND = 148
  OUT_SNOW_MELT_BAND = 149
  OUT_SNOW_PACKT_BAND = 150
  OUT_SNOW_SURFT_BAND = 151
  OUT_SWE_BAND = 152
  OUT_APAR = 153
  OUT_GPP = 154
  OUT_RAUT = 155
  OUT_NPP = 156
  OUT_LITTERFALL = 157
  OUT_RHET = 158
  OUT_NEE = 159
  OUT_CLITTER = 160
  OUT_CINTER = 161
  OUT_CSLOW = 162
  OUT_TIME_VICRUN_WALL = 163
  OUT_TIME_VICRUN_CPU = 164
  N_OUTVAR_TYPES = 165
end

@cenum var"##Ctag#2162"::UInt32 begin
  STATE_SOIL_MOISTURE = 0
  STATE_SOIL_ICE = 1
  STATE_CANOPY_WATER = 2
  STATE_ANNUALNPP = 3
  STATE_ANNUALNPPPREV = 4
  STATE_CLITTER = 5
  STATE_CINTER = 6
  STATE_CSLOW = 7
  STATE_SNOW_AGE = 8
  STATE_SNOW_MELT_STATE = 9
  STATE_SNOW_COVERAGE = 10
  STATE_SNOW_WATER_EQUIVALENT = 11
  STATE_SNOW_SURF_TEMP = 12
  STATE_SNOW_SURF_WATER = 13
  STATE_SNOW_PACK_TEMP = 14
  STATE_SNOW_PACK_WATER = 15
  STATE_SNOW_DENSITY = 16
  STATE_SNOW_COLD_CONTENT = 17
  STATE_SNOW_CANOPY = 18
  STATE_SOIL_NODE_TEMP = 19
  STATE_FOLIAGE_TEMPERATURE = 20
  STATE_ENERGY_LONGUNDEROUT = 21
  STATE_ENERGY_SNOW_FLUX = 22
  STATE_LAKE_SOIL_MOISTURE = 23
  STATE_LAKE_SOIL_ICE = 24
  STATE_LAKE_CLITTER = 25
  STATE_LAKE_CINTER = 26
  STATE_LAKE_CSLOW = 27
  STATE_LAKE_SNOW_AGE = 28
  STATE_LAKE_SNOW_MELT_STATE = 29
  STATE_LAKE_SNOW_COVERAGE = 30
  STATE_LAKE_SNOW_WATER_EQUIVALENT = 31
  STATE_LAKE_SNOW_SURF_TEMP = 32
  STATE_LAKE_SNOW_SURF_WATER = 33
  STATE_LAKE_SNOW_PACK_TEMP = 34
  STATE_LAKE_SNOW_PACK_WATER = 35
  STATE_LAKE_SNOW_DENSITY = 36
  STATE_LAKE_SNOW_COLD_CONTENT = 37
  STATE_LAKE_SNOW_CANOPY = 38
  STATE_LAKE_SOIL_NODE_TEMP = 39
  STATE_LAKE_ACTIVE_LAYERS = 40
  STATE_LAKE_LAYER_DZ = 41
  STATE_LAKE_SURF_LAYER_DZ = 42
  STATE_LAKE_DEPTH = 43
  STATE_LAKE_LAYER_SURF_AREA = 44
  STATE_LAKE_SURF_AREA = 45
  STATE_LAKE_VOLUME = 46
  STATE_LAKE_LAYER_TEMP = 47
  STATE_LAKE_AVERAGE_TEMP = 48
  STATE_LAKE_ICE_AREA_FRAC = 49
  STATE_LAKE_ICE_AREA_FRAC_NEW = 50
  STATE_LAKE_ICE_WATER_EQUIVALENT = 51
  STATE_LAKE_ICE_HEIGHT = 52
  STATE_LAKE_ICE_TEMP = 53
  STATE_LAKE_ICE_SWE = 54
  STATE_LAKE_ICE_SNOW_SURF_TEMP = 55
  STATE_LAKE_ICE_SNOW_PACK_TEMP = 56
  STATE_LAKE_ICE_SNOW_COLD_CONTENT = 57
  STATE_LAKE_ICE_SNOW_SURF_WATER = 58
  STATE_LAKE_ICE_SNOW_PACK_WATER = 59
  STATE_LAKE_ICE_SNOW_ALBEDO = 60
  STATE_LAKE_ICE_SNOW_DEPTH = 61
  STATE_AVG_ALBEDO = 62
  N_STATE_VARS = 63
end

@cenum var"##Ctag#2163"::UInt32 begin
  OUT_TYPE_DEFAULT = 0
  OUT_TYPE_CHAR = 1
  OUT_TYPE_SINT = 2
  OUT_TYPE_USINT = 3
  OUT_TYPE_INT = 4
  OUT_TYPE_FLOAT = 5
  OUT_TYPE_DOUBLE = 6
end

@cenum var"##Ctag#2164"::UInt32 begin
  AGG_TYPE_DEFAULT = 0
  AGG_TYPE_AVG = 1
  AGG_TYPE_BEG = 2
  AGG_TYPE_END = 3
  AGG_TYPE_MAX = 4
  AGG_TYPE_MIN = 5
  AGG_TYPE_SUM = 6
end

@cenum var"##Ctag#2165"::UInt32 begin
  FREQ_NEVER = 0
  FREQ_NSTEPS = 1
  FREQ_NSECONDS = 2
  FREQ_NMINUTES = 3
  FREQ_NHOURS = 4
  FREQ_NDAYS = 5
  FREQ_NMONTHS = 6
  FREQ_NYEARS = 7
  FREQ_DATE = 8
  FREQ_END = 9
end

@cenum var"##Ctag#2166"::UInt32 begin
  DISP_VERSION = 0
  DISP_COMPILE_TIME = 1
  DISP_ALL = 2
end

@cenum calendars::UInt32 begin
  CALENDAR_STANDARD = 0
  CALENDAR_GREGORIAN = 1
  CALENDAR_PROLEPTIC_GREGORIAN = 2
  CALENDAR_NOLEAP = 3
  CALENDAR_365_DAY = 4
  CALENDAR_360_DAY = 5
  CALENDAR_JULIAN = 6
  CALENDAR_ALL_LEAP = 7
  CALENDAR_366_DAY = 8
end

@cenum time_units::UInt32 begin
  TIME_UNITS_SECONDS = 0
  TIME_UNITS_MINUTES = 1
  TIME_UNITS_HOURS = 2
  TIME_UNITS_DAYS = 3
end

@cenum timers::UInt32 begin
  TIMER_VIC_ALL = 0
  TIMER_VIC_INIT = 1
  TIMER_VIC_RUN = 2
  TIMER_VIC_FINAL = 3
  TIMER_VIC_FORCE = 4
  TIMER_VIC_WRITE = 5
  N_TIMERS = 6
end




@cenum var"##Ctag#2132"::UInt32 begin
  DENS_BRAS = 0
  DENS_SNTHRM = 1
end

@cenum var"##Ctag#2133"::UInt32 begin
  ARNO = 0
  NIJSSEN2001 = 1
end

@cenum var"##Ctag#2134"::UInt32 begin
  AR_406 = 0
  AR_406_LS = 1
  AR_406_FULL = 2
  AR_410 = 3
end

@cenum var"##Ctag#2135"::UInt32 begin
  GF_406 = 0
  GF_410 = 1
end

@cenum var"##Ctag#2136"::UInt32 begin
  RC_JARVIS = 0
  RC_PHOTO = 1
end

@cenum var"##Ctag#2137"::UInt32 begin
  PS_FARQUHAR = 0
  PS_MONTEITH = 1
end

@cenum var"##Ctag#2138"::UInt32 begin
  PHOTO_C3 = 0
  PHOTO_C4 = 1
end
